### ISSUE TITLE
[Bug] "Half mining" = false causes slab duping

### ISSUE THREAD

**Issue by supersaiyansubtlety** [jingshenSN2/SlabHelper#1]
If I disable "Half mining" 
_(enabling half mining for all tools, rather confusing, mabye consider calling it "universal half mining" and making true mean all tools can half mine?)_, 
when I break only half of a double slab with a normal tool, it drops two slabs while leaving a single slab behind as expected. 
Obviously this is item duplication as I can then place one of the two dropped slabs to restore the double slab, break again and repeat.

**Comment by jingshenSN2** [comment]
try v1.1.1, I think I will totally delete the slab pickaxe and only keep the ''universal half mining" option in the next version.

**Comment by supersaiyansubtlety** [comment]
Works like a charm, thanks a bunch!
