### ISSUE TITLE
[1.16.2] SlabHelper crash when placing slabs. (Server.)

### ISSUE THREAD

**Issue by Gbergz** [jingshenSN2/SlabHelper#2]
Title^

**Crash-Report:** https://pastebin.com/rpLfh6xH

**Minecraft:** 1.16.2
**Slab Helper Version:** 1.3.3
**Fabric API Version:** 0.19.0+build.398-1.16

**-** Gbergz

**Comment by jingshenSN2** [comment]
seems like it's caused by a change in function name in the latest Fabric API (when I uploaded slabhelepr 1.3.3, the Fabric API was in 0.17.2). I will upload a new version based on Fabric API 0.20.1 instead.
